### ISSUE TITLE
no way to exculde systerm volume and recycle bin so unable to robo copy a whole drive

### ISSUE THREAD

**Issue by mat43211** [Cinchoo/ChoEazyCopy#51]
please can you make a way to put /xd $RECYCLE.BIN "System Volume Information" at the end of the command so that it skips recycle bin and systerm volume so that when copying a whole drive to other I am able to copy

**Comment by beng-tang** [comment]
I have the same issue. The ExcludeDirsWithGivenNames option in the control panel only allows specifying one directory name because it encloses everything in the file with double quotes. So instead of getting /xd $RECYCLE.BIN "System Volume Information" I get /xd "$RECYCLE.BIN "System Volume Information"" on the command line string.

**Comment by beng-tang** [comment]
Update: I found a workaround: instead of using ExcludeDirsWithGivenNames in the control panel, use the AdditionalParms field at the top of the pannel, and put in it:
/XD $RECYCLE.BIN Recovery "System Volume Information"
